# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_3J9XQuyXvpTVd73ySjnLWKtidmnJsG
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt

IMG_SIZE = 224
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

(ds_train, ds_val, ds_test), info = tfds.load(
    "beans",
    split=["train", "validation", "test"],
    as_supervised=True,
    with_info=True
)

num_classes = info.features["label"].num_classes
class_names = info.features["label"].names

print("Classes:", class_names)
print("Train size:", info.splits["train"].num_examples)
print("Val size:", info.splits["validation"].num_examples)
print("Test size:", info.splits["test"].num_examples)

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.05),
    tf.keras.layers.RandomZoom(0.1),
])

def preprocess(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    return image, label   # no /255.0 here

def make_ds(ds, training=False):
    ds = ds.map(preprocess, num_parallel_calls=AUTOTUNE)
    if training:
        ds = ds.shuffle(1000)
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y),
                    num_parallel_calls=AUTOTUNE)
    ds = ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)
    return ds

train_ds = make_ds(ds_train, training=True)
val_ds   = make_ds(ds_val, training=False)
test_ds  = make_ds(ds_test, training=False)

base_model = tf.keras.applications.MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs)
x = base_model(x, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(0.3)(x)
outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)

model = tf.keras.Model(inputs, outputs)

base_model.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

EPOCHS_FROZEN = 5

history_frozen = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_FROZEN
)

base_model.trainable = True

fine_tune_at = int(len(base_model.layers) * 0.8)
print("Total layers:", len(base_model.layers))
print("Fine-tuning from layer:", fine_tune_at)

for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(5e-5),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

EPOCHS_FINE = 20

history_finetune = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_FINE
)

test_loss, test_acc = model.evaluate(test_ds)
print("Test accuracy:", test_acc)

import numpy as np
import matplotlib.pyplot as plt

# get one batch from test_ds
images, labels = next(iter(test_ds))   # images: (B, 224, 224, 3)

# run model predictions
preds = model.predict(images)
pred_labels = np.argmax(preds, axis=1)

# how many images to show (max 9 or batch size)
n_show = min(9, images.shape[0])

plt.figure(figsize=(12, 10))
for i in range(n_show):
    plt.subplot(3, 3, i+1)

    # convert to uint8 for nicer display (images are still in 0-255 range)
    img = images[i].numpy().astype("uint8")
    plt.imshow(img)

    true_idx = int(labels[i].numpy())
    pred_idx = int(pred_labels[i])

    true_label = class_names[true_idx]
    pred_label = class_names[pred_idx]

    title = f"T: {true_label}\nP: {pred_label}"
    plt.title(title)
    plt.axis("off")

plt.tight_layout()
plt.show()

