# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ei8ya0TkyzALo7QUDVd68MBitCulTsR
"""

# 1. Install ultralytics (YOLOv8) and supporting libs
!pip install -q ultralytics==8.0.XXX  # if you want latest, remove version; replace XXX with desired or leave out
!pip install -q wandb    # optional, only if you want W&B logging

# 2. Check GPU
import torch
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

!pip install ultralytics

# 1. Install ultralytics (YOLOv8) and supporting libs
!pip install -q ultralytics
!pip install -q wandb    # optional, can remove if you don't want W&B

# 2. Check GPU
import torch
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

# Commented out IPython magic to ensure Python compatibility.
# Cell 1 — Setup: install deps and clone repo
# Run this first. It installs requirements used in most official tutorials.
!git clone https://github.com/ultralytics/yolov5.git
# %cd yolov5
!pip install -r requirements.txt
# (Optional) upgrade pip / torch if needed — Colab usually has recent PyTorch.

# Cell 2 — Quick GPU check
import torch
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    try:
        print("Device:", torch.cuda.get_device_name(0))
    except Exception:
        pass

# Cell 3 — (Optional) Mount Google Drive to save runs / load datasets
from google.colab import drive
print("Mounting Drive (optional). If you don't want to mount, interrupt/skip cell.")
drive.mount('/content/drive')
# Example save dir: /content/drive/MyDrive/yolov5_runs

# Cell 4 — Quick test train on built-in coco128 (fast demo)
# This will automatically download the coco128 dataset and pretrained weights if needed.
# Recommended: set epochs small for a quick run (e.g., 3-30). Increase for real training.
!python train.py --img 640 --batch 16 --epochs 30 --data coco128.yaml --weights yolov5s.pt --project runs/train --name yolov5_coco128_demo

# Cell 5 — Validate the trained model (uses best weights saved under runs/train/<name>/weights/best.pt)
# Replace <name> if you changed it in the previous cell
BEST = 'runs/train/yolov5_coco128_demo/weights/best.pt'
import os
if os.path.exists(BEST):
    !python val.py --weights {BEST} --data coco128.yaml --img 640 --batch 16
else:
    print("Best weights not found. Check run folder name or training succeeded.")

# Cell 6 — Inference / prediction on an image or folder (saves to runs/detect/)
# You can use a local image, a URL, or a folder of images.
!python detect.py --weights runs/train/yolov5_coco128_demo/weights/best.pt --source https://ultralytics.com/images/zidane.jpg --img 640 --conf 0.25 --save-txt --save-conf
# Results saved under runs/detect/

# Cell 7 — Show the saved prediction image (simple display)
from IPython.display import Image, display
import glob
imgs = glob.glob('runs/detect/*/*.jpg')  # adjust if multiple detect runs
if imgs:
    display(Image(imgs[0]))
else:
    print("No detect images found. Check detect.py output.")

# Cell 9 — Copy best weights to Google Drive (if mounted)
drive_dest = '/content/drive/MyDrive/yolov5_runs'
os.makedirs(drive_dest, exist_ok=True)
if os.path.exists('runs/train/yolov5_coco128_demo/weights/best.pt'):
    import shutil
    shutil.copy('runs/train/yolov5_coco128_demo/weights/best.pt', drive_dest)
    print("Copied best.pt to Drive:", drive_dest)
else:
    print("best.pt not found")